### PR TITLE
Move Fedora's brp-mangle-shebangs from fedora-python/brp-mangle-shebangs

### PR DESCRIPTION
**Pull request by hroncok**
Also, please activate Travis CI for this repository.

### CODE REVIEW

**Comment by Conan-Kudo** [comment]
@hroncok We probably won't use Travis CI here. RPM itself uses Semaphore CI, and we will likely do the same for this.

**Comment by hroncok** [comment]
Whatever CI you want. Just please have some. Our repo had it and I'm moving this here as requested in https://src.fedoraproject.org/rpms/redhat-rpm-config/pull-request/31

**Comment by Conan-Kudo** [comment]
@hroncok You know this repo isn't packaged, right?

**Comment by hroncok** [comment]
yes, the file lives in dist git of redhat-rpm-config. I just happen to have tests for it that nobody wants, so I created my own "upstream" and wanted a link to that upstream in redhat-rpm-config spec, so whoever changes the brp script is aware of the tests, but the link was rejected, such scripts already have a repo and that is this one.

All I really want is a place where the tests can be and than a link in the spec that links to them + a place where people can send changes and have the tests be run.

**Comment by Conan-Kudo** [comment]
@hroncok Other than the Travis CI commit, this looks fine to me. Can you please remove the Travis CI commit and rebase on current master?

**Comment by hroncok** [comment]
Like this or even more rebasing? Note that it will not be trivial (there are files that conflict before I move them around, so I'd need to filter branch or something).

**Comment by Conan-Kudo** [comment]
@hroncok Basically, `git rebase upstream/master`. Though I'm not sure how this branch is set up as it is...

**Comment by hroncok** [comment]
Rebased manually commit by commit. Better now?

**Comment by hroncok** [comment]
Actually, wait a minute or five.

**Comment by hroncok** [comment]
This is as good as it gets.

**Review by Conan-Kudo — APPROVED** [review]
LGTM

**Comment by Conan-Kudo** [comment]
@hroncok Merged, thanks!

**Pull request merged**
